# build environment
FROM node:13.12.0-alpine as build
WORKDIR /app
# ENV PATH /app/node_modules/.bin:$PATH
ENV REACT_APP_API_URL=https://api-ertg25.herokuapp.com
COPY package*.json ./
RUN npm ci --silent
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /var/wwww
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
# new
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]